### ISSUE TITLE
Лабораторная работа №2

### ISSUE THREAD

**Issue by LokoElena** [LokoElena/Lab2#1]
Выполнила студентка гр. ИС-541
Копылова Елена
@evgeny-p

**Comment by evgeny-p** [comment]
1. Неконсистентное форматирование:
   1. Бинарные операторы должны быть выделены пробелами.
   2. После запятой ставится пробел.
   3. При вызове функции в некоторых случаях стоит пробел перед открывающей круглой скобкой, в некоторых — нет. Поскольку это математическая запись, пробел не ставится.
   4. В конце строки 29 лишние пробелы.
   5. Строки 24−25 написаны c лишним отступом.
   6. Между операторами и открывающей круглой скобкой в некоторых случаях стоит пробел, в некоторых — нет. В этих случаях обычно применяются правила типографики текстов на естественном языке, т.е. пробел перед открывающей скобкой ставится.
2. Критерий определения количества корней — значение дискриминанта, а вычисленных корней.
3. Числа с плавающей точкой должны сравниваться с заданной точностью, см.  https://github.com/Doshinsky/Lab-2/issues/1#issuecomment-189645601.

Все исправления должны соответствовать требованиям к основному заданию: т.е. должны быть выполнены в отдельной ветке, каждый коммит содержит одну независимую порцию изменений. Не допускается смешивание исправлений форматирования и функциональных изменений в одном коммите. Но в одном коммите могут быть выполнены все исправления форматирования.

**Comment by LokoElena** [comment]
@evgeny-p
Думаю, все замечания учтены

**Comment by evgeny-p** [comment]
В последнем коммите слишком много изменений: объединены как изменения форматирования, так и функциональные. При этом в заголовке коммита указано очень общее «code debug», не характеризующее изменения. В последующих работах постарайтесь оформлять независимые и самодостаточные изменения в отдельные коммиты. Серия коммитов, объединенных одной задачей, оформляется в ветку.

Работа принята.
